# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
