# Generated by Django 2.1 on 2021-04-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='PhoneNumber',
        ),
    ]
