# Generated by Django 2.1 on 2021-04-06 19:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0002_remove_apartment_phonenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='apartment',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
