# Generated by Django 2.1 on 2021-04-06 19:46

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0003_auto_20210406_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='location',
        ),
        migrations.AddField(
            model_name='apartment',
            name='location_has_default',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-104.9903, 39.7392), srid=4326),
        ),
    ]
