# Generated by Django 2.1 on 2021-04-06 20:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0004_auto_20210406_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='location_has_default',
        ),
        migrations.AddField(
            model_name='apartment',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
