# Generated by Django 2.1 on 2021-04-06 21:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0005_auto_20210406_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
