# Generated by Django 2.1 on 2021-04-07 11:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0006_auto_20210406_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
