# Generated by Django 2.1 on 2021-04-07 11:30

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0007_auto_20210407_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(36.38, -0.7), geography=True, srid=4326),
        ),
    ]
