# Generated by Django 3.2 on 2021-04-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0008_auto_20210407_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='apartment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
