# Generated by Django 3.2 on 2021-04-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0009_receipt_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='apartment',
            field=models.CharField(blank=True, default='Smile', max_length=50, null=True),
        ),
    ]
