# Generated by Django 3.2 on 2021-04-09 09:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0010_alter_receipt_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=30000, null=True),
        ),
    ]
