# Generated by Django 3.2 on 2021-06-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0011_alter_apartment_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartment',
            new_name='Shelter',
        ),
    ]
