# Generated by Django 3.2 on 2021-07-02 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0012_rename_apartment_shelter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='price',
        ),
    ]
