# Generated by Django 3.2 on 2021-07-02 06:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0013_remove_shelter_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='contact',
            field=ckeditor.fields.RichTextField(blank=True, max_length=30000, null=True),
        ),
    ]
