# Generated by Django 3.2.6 on 2021-08-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0016_rename_bookings_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='shelter_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
