# Generated by Django 3.2.6 on 2021-08-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0017_booking_shelter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterBookingCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_times', models.PositiveIntegerField()),
            ],
        ),
    ]
