# Generated by Django 3.2.6 on 2021-08-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0018_shelterbookingcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShelterBookingCount',
        ),
    ]
