# Generated by Django 3.2.6 on 2021-08-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0019_delete_shelterbookingcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterBookingCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_times', models.PositiveIntegerField()),
                ('name', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='registratione.shelter')),
            ],
        ),
    ]
