# Generated by Django 3.2.6 on 2021-08-04 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registratione', '0020_shelterbookingcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelterbookingcount',
            name='name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registratione.shelter'),
        ),
    ]
